# Generated by Django 4.0.5 on 2022-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
        ),
    ]
